version: '3'
services:
  helloworld:
    image: arnoxuweichu/helloworld:1.0
  arnoxunginx:
    image: arnoxuweichu/arnoxunginx:1.0
    ports:
    - "5001:80"
  mycat:
    image: arnoxuweichu/cat:1.0
    ports:
    - "5000:5000"
